apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hypertheory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jeffrygonzalez/frontend-july-2023:v0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
